// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: acme/v1/acme.proto

package pbacmeconnect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	v1 "github.com/streamingfast/dgrpc/examples/internal/pb/acme/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PingPongServiceName is the fully-qualified name of the PingPongService service.
	PingPongServiceName = "acme.v1.PingPongService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PingPongServiceGetPingProcedure is the fully-qualified name of the PingPongService's GetPing RPC.
	PingPongServiceGetPingProcedure = "/acme.v1.PingPongService/GetPing"
	// PingPongServiceStreamPingProcedure is the fully-qualified name of the PingPongService's
	// StreamPing RPC.
	PingPongServiceStreamPingProcedure = "/acme.v1.PingPongService/StreamPing"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	pingPongServiceServiceDescriptor          = v1.File_acme_v1_acme_proto.Services().ByName("PingPongService")
	pingPongServiceGetPingMethodDescriptor    = pingPongServiceServiceDescriptor.Methods().ByName("GetPing")
	pingPongServiceStreamPingMethodDescriptor = pingPongServiceServiceDescriptor.Methods().ByName("StreamPing")
)

// PingPongServiceClient is a client for the acme.v1.PingPongService service.
type PingPongServiceClient interface {
	GetPing(context.Context, *connect.Request[v1.GetPingRequest]) (*connect.Response[v1.PingResponse], error)
	StreamPing(context.Context, *connect.Request[v1.StreamPingRequest]) (*connect.ServerStreamForClient[v1.PingResponse], error)
}

// NewPingPongServiceClient constructs a client for the acme.v1.PingPongService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPingPongServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PingPongServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &pingPongServiceClient{
		getPing: connect.NewClient[v1.GetPingRequest, v1.PingResponse](
			httpClient,
			baseURL+PingPongServiceGetPingProcedure,
			connect.WithSchema(pingPongServiceGetPingMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		streamPing: connect.NewClient[v1.StreamPingRequest, v1.PingResponse](
			httpClient,
			baseURL+PingPongServiceStreamPingProcedure,
			connect.WithSchema(pingPongServiceStreamPingMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// pingPongServiceClient implements PingPongServiceClient.
type pingPongServiceClient struct {
	getPing    *connect.Client[v1.GetPingRequest, v1.PingResponse]
	streamPing *connect.Client[v1.StreamPingRequest, v1.PingResponse]
}

// GetPing calls acme.v1.PingPongService.GetPing.
func (c *pingPongServiceClient) GetPing(ctx context.Context, req *connect.Request[v1.GetPingRequest]) (*connect.Response[v1.PingResponse], error) {
	return c.getPing.CallUnary(ctx, req)
}

// StreamPing calls acme.v1.PingPongService.StreamPing.
func (c *pingPongServiceClient) StreamPing(ctx context.Context, req *connect.Request[v1.StreamPingRequest]) (*connect.ServerStreamForClient[v1.PingResponse], error) {
	return c.streamPing.CallServerStream(ctx, req)
}

// PingPongServiceHandler is an implementation of the acme.v1.PingPongService service.
type PingPongServiceHandler interface {
	GetPing(context.Context, *connect.Request[v1.GetPingRequest]) (*connect.Response[v1.PingResponse], error)
	StreamPing(context.Context, *connect.Request[v1.StreamPingRequest], *connect.ServerStream[v1.PingResponse]) error
}

// NewPingPongServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPingPongServiceHandler(svc PingPongServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pingPongServiceGetPingHandler := connect.NewUnaryHandler(
		PingPongServiceGetPingProcedure,
		svc.GetPing,
		connect.WithSchema(pingPongServiceGetPingMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	pingPongServiceStreamPingHandler := connect.NewServerStreamHandler(
		PingPongServiceStreamPingProcedure,
		svc.StreamPing,
		connect.WithSchema(pingPongServiceStreamPingMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/acme.v1.PingPongService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PingPongServiceGetPingProcedure:
			pingPongServiceGetPingHandler.ServeHTTP(w, r)
		case PingPongServiceStreamPingProcedure:
			pingPongServiceStreamPingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPingPongServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPingPongServiceHandler struct{}

func (UnimplementedPingPongServiceHandler) GetPing(context.Context, *connect.Request[v1.GetPingRequest]) (*connect.Response[v1.PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("acme.v1.PingPongService.GetPing is not implemented"))
}

func (UnimplementedPingPongServiceHandler) StreamPing(context.Context, *connect.Request[v1.StreamPingRequest], *connect.ServerStream[v1.PingResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("acme.v1.PingPongService.StreamPing is not implemented"))
}
